name: DVC-NLP-Project

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest] # runs on ubuntu os
    steps:
      - uses: actions/checkout@v2 # 
      - uses: iterative/setup-cml@v1 # iterative is a company which runs dvc to setup cml
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: cml-run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        runs: |
          # Your ML workflow commands
          pip install --upgrade pip
          pip install -r requirements.txt
          
          dvc repro -v

          echo "# REPORTS " >> report.md
          echo "## metrics" >> report.md
          cat score.json >> report.md

          cml-send-comment report.md



