name: DVC-NLP-Project

on: [push]

jobs:

  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: 'Deploy runner in EC2'
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO_TOKEN: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REPO_TOKEN: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --clour-type=m \
          --labels=cml-runner
  
  install-requirements:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: docker://iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: 'prepare environment'
        env:
          repo_token: ${{ secrets.PERSONAL_TOKEN }}
        runs: |
          pip install --upgrade pip
          pip install -r requirements.txt

  model-taining:
    need: install-requirements
    runs-on: [self-hosted, cml-runner]
    container: docker://iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: 'Train and publish results'
        env:
          repo_token: ${{ secrets.PERSONAL_TOKEN }}
        runs: |
          dvc repro 
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          dvc metrics show >> report.md
          cml-send-comment report.md
